name: rimes_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  firebase_core: ^4.1.0
  web_socket_channel: ^3.0.3
  sqflite: ^2.4.2
  path: ^1.9.1
  fl_chart: ^1.1.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  vector_math: ^2.2.0
  flutter_secure_storage: ^9.2.4
  socket_io_client: ^3.1.2
  fluttertoast: ^8.2.12
  flutter_heatmap_calendar: ^1.0.5
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.1
  firebase_messaging: ^16.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
